export const TECH_META = {
  'reactjs':         { label: 'React',           color: '#61DAFB' },
  'typescript':      { label: 'TypeScript',       color: '#3178C6' },
  'javascript':      { label: 'JavaScript',       color: '#F7DF1E' },
  'html':            { label: 'HTML',             color: '#E34F26' },
  'css':             { label: 'CSS',              color: '#264DE4' },
  'tailwind':        { label: 'Tailwind',         color: '#06B6D4' },
  'vite':            { label: 'Vite',             color: '#646CFF' },
  'bootstrap':       { label: 'Bootstrap',        color: '#7952B3' },
  'redux':           { label: 'Redux',            color: '#764ABC' },
  'tanstack-query':  { label: 'TanStack Query',   color: '#FF4154' },
  'rsuite':          { label: 'RSuite',           color: '#3498DB' },
  'nodejs':          { label: 'Node.js',          color: '#339933' },
  'nestjs':          { label: 'NestJS',           color: '#E0234E' },
  'dotnet':          { label: '.NET',             color: '#512BD4' },
  'java':            { label: 'Java',             color: '#ED8B00' },
  'spring-boot':     { label: 'Spring Boot',      color: '#6DB33F' },
  'spring-security': { label: 'Spring Security',  color: '#6DB33F' },
  'sql':             { label: 'SQL',              color: '#4479A1' },
  'prisma':          { label: 'Prisma',           color: '#5A67D8' },
  'supabase':        { label: 'Supabase',         color: '#3ECF8E' },
  'hibernate':       { label: 'Hibernate',        color: '#59666C' },
  'api-rest':        { label: 'REST API',         color: '#10B981' },
};
